# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Get firmware source code
      uses: actions/checkout@v2
      with:
        path: src
        submodules: true

    # Runs a single command using the runners shell
    - name: Install Dependencies
      run: |
        # latest = https://www.microchip.com/mplabxc16linux
        # current = http://ww1.microchip.com/downloads/en/DeviceDoc/xc16-v1.50-full-install-linux64-installer.run 
        curl --output xc16-linux-installer.run --silent https://ww1.microchip.com/downloads/en/DeviceDoc/xc16-v1.50-full-install-linux64-installer.run
        chmod +x xc16-linux-installer.run
        sudo ./xc16-linux-installer.run --mode unattended --netservername "" --debuglevel 4
        sudo apt install doxygen graphviz

    # Runs a set of commands using the runners shell
    - name: Build firmware
      run: |
        mkdir build
        cmake -S $GITHUB_WORKSPACE/src -B ${GITHUB_WORKSPACE}/build
        cmake --build ${GITHUB_WORKSPACE}/build
