name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache downloads
        uses: actions/cache@v1
        with:
          path: downloads
          key: ${{ runner.os }}-downloads

      - name: Install Dependencies
        run: |
          mkdir -p downloads
          [[ ! -f $XC16_INSTALLER ]] && curl --silent --output $XC16_INSTALLER $XC16_INSTALLER_URL
          chmod +x $XC16_INSTALLER
          sudo $XC16_INSTALLER --mode unattended --netservername ""
          sudo apt install doxygen graphviz
        env:
          XC16_INSTALLER: downloads/xc16-linux-installer.run
          # latest = https://www.microchip.com/mplabxc16linux
          # current = http://ww1.microchip.com/downloads/en/DeviceDoc/xc16-v1.50-full-install-linux64-installer.run 
          XC16_INSTALLER_URL: https://ww1.microchip.com/downloads/en/DeviceDoc/xc16-v1.50-full-install-linux64-installer.run

      - name: Get firmware source code
        uses: actions/checkout@v2
        with:
          path: src
          submodules: true

      # - name: Build firmware
      #   run: |
      #     mkdir build
      #     cmake -S src -B build -DCMAKE_TOOLCHAIN_FILE="$(pwd)/src/cmake/PowerBoard_toolchain.cmake"
      #     cmake --build build --target package

      # - name: Upload build folder (for debuggirg)
      #   uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: build
      #     path: build

      # - name: Upload built firmware
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: packaged
      #     path: build/OpenRoverFirmware-*.zip
      
      - name: Build firmware
        run: |
          mkdir build
          cmake -S src -B build -DCMAKE_TOOLCHAIN_FILE="$(pwd)/src/cmake/PowerBoard_toolchain.cmake"
          cmake --build build --install install

      - name: Upload build folder (for debuggirg)
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: build
          path: build

      - name: Upload install folder
        uses: actions/upload-artifact@v2
        with:
          name: install
          path: install

